### PR TITLE
add simple WWAN support. Enable/Disable.

### PR DESCRIPTION
**Pull request by cyrinux**
Is it good as this man? The goal is simply to have minimal feature to enable or disable the WWAN.

ps: previous bad PR here https://github.com/firecat53/networkmanager-dmenu/pull/50

### CODE REVIEW

**Comment by cyrinux** [comment]
Hi @firecat53 is it good for you like this? 😃

**Comment by firecat53** [comment]
It looks like all you really want to add is the ability to disable/enable the wwan modem. I think you added some extra complexity that isn't needed. Let me work on it a bit, and then you can test it to see if it does what you want. I can't test it here because I don't have a cellular modem! Thanks

**Comment by cyrinux** [comment]
Hi @firecat53 
Yes I want to disable/enable it, but I have a friend which use your project and doesn't have a wwan modem.
When he tries previous commit he see the WWAN option.
It is why I want to be proper and only display the option when ModemManager is installed.

If you want / can enable disable WWAN support via a param this could be an option ;)

Tell me :)

**Comment by cyrinux** [comment]
Hmm I just react I have a bug in this PR, I dont get the marker which say on which connection I'm connected 👎

**Comment by cyrinux** [comment]
@firecat53, I'm dumb, compared to my previous remark, it is was only a miss config, I have set `rofi_highlight` to `True`, and was searching `**` ... sorry.

**Comment by firecat53** [comment]
Give it a try now and make sure it works for you. Thanks for the PR!

**Comment by cyrinux** [comment]
Thanks 🙏 will try tomorrow

**Comment by cyrinux** [comment]
Works well :) Thanks!

**Pull request closed without merging**
