### PR TITLE
Any of dmenu argument can be passed.

### PR DESCRIPTION
**Pull request by sudo97**
Maybe it is not safe, or even stupid, but this is, I think, a good way to be able to put it into other scripts and customize appearance. When I did this, I wanted to write `exec networkmanager_dmenu -b` into my i3-config file, but i couldn't. and now i can:-)

### CODE REVIEW

**Comment by firecat53** [comment]
So, you can already do this inside the config file. If you set the `dmenu_command` option, you can pass whatever dmenu arguments you desire :) There's even a specific comment about setting the `-b` flag.

Give it a try and let me know if that works for you.

**Comment by sudo97** [comment]
Can I use config to make networkmanager_dmenu appear different ways in different circumstances?

For example I want it to appear on top when I press Ctrl+D and type netwowkmanager_dmenu in my i3
and I want it to appear on bottom when I mouse-press the i3status bar, so it would be different bindings inside .config/i3/config, or any other.

Maybe, should I improve my version to replace config's settings if any arguments being pased?

Thanks for the fast reply.

I almost haven't did it before(not at all), but I found very satisfying using python in my life, so thank you:-)

**Comment by firecat53** [comment]
Ah, I understand now what you're trying to do. I'll take a look at it again.

**Comment by sudo97** [comment]
It is only one additional line now, maybe I should do it in more safe and accurate way. Haven't tested it with conflicting config settings or so

**Comment by firecat53** [comment]
Merged! Added a README note as well. Thanks!

**Comment by sudo97** [comment]
When is this going to appear on the AUR?

**Comment by firecat53** [comment]
Just update your package. Git packages are rebuilt with the latest version when you build it. There aren't updates per session unless something changes in the PKGBUILD.

**Pull request closed without merging**
