### PR TITLE
feat: customizable active prefix & highlighting style for wofi

### PR DESCRIPTION
**Pull request by Alan-Kuan**
I added 2 features.

1. customizable active prefix
```ini
[dmenu]
active_chars = v  # (default: ==)
```

image

2. highlight active connection and customizable style for wofi
I don't use other menus, and don't know whether it's possible there, so I only support wofi.

> **Warning**
> There's a breaking change. I renamed `rofi_highlight` to `highlight`.
> In my opinion, it's better than introducing another `wofi_highlight` field.

```ini
[dmenu]
highlight = True
```

image
> Default highlighting style is bold text.

The followings are fields for the highlighting style.

```ini
[dmenu]
highlight_fg = #f2b468
highlight_bg = black
highlight_bold = False
```

image

Please tell me what to do if I missed something. Thank you!

### CODE REVIEW

**Comment by Alan-Kuan** [comment]
Hi @firecat53,

Could you take a look at this and help me merge it?
Thank you so much.

**Comment by firecat53** [comment]
Patience my friend 😉 I will get to it when I have some free time. Thanks for the contribution!

**Comment by Alan-Kuan** [comment]
Thanks. I can wait until you're available.

**Comment by joelsleeba** [comment]
@Alan-Kuan I had implemented almost similar thing locally. Appreciate this pull request

**Pull request merged**
