### PR TITLE
use "/usr/bin/env python3" to run script

### PR DESCRIPTION
**Pull request by legrostdg**
indicate that networkmanager_dmenu is python3 only

### CODE REVIEW

**Comment by firecat53** [comment]
I appreciate the interest! However, given that Python 2 is no longer supported, my intent is to support Python 3 as the default...meaning that the command will just be `python`. I recognize that this is still not the case in some distros, but it will be. Until then, users will need to adjust the shebang command as necessary to run it using python 3. Thanks!

**Comment by legrostdg** [comment]
At least on Debian, there is no plan before a long time (>10years) to provide an alias python3 -> python. I don't understand the rationale... If the script only supports python3, why don't inform the user directly with `/usr/bin/env python3`? https://www.python.org/dev/peps/pep-0394/

**Comment by firecat53** [comment]
Although it still feels to me like `python` should always point to the most recent version, I will bow to the recommendations of the PEP to use `python3` for scripts. Thanks for the link!

**Comment by legrostdg** [comment]
Great, thanks!

**Pull request merged**
