### PR TITLE
Adds option to list saved connections

### PR DESCRIPTION
**Pull request by zzzdeb**
refering to this issue:
https://github.com/firecat53/networkmanager-dmenu/issues/72

### CODE REVIEW

**Comment by firecat53** [comment]
Thanks for the PR!

Another solution could be adding a menu entry at the bottom to `Show saved connections` that opens a separate list of just saved connections and not needing another config option. It's just an idea...which do you think would be better/easier for the users?

Also, what do you think about moving the saved list below the menu items so the menu items (delete, rescan, etc) are more visible?

Finally, can you please update the README to reflect whatever changes we decide on?

Thanks!!

**Comment by zzzdeb** [comment]
With pleasure!

Adding submenu is at least for me undesirable. For now, with ~3 letters, I am able to find my desired network and I think, it is in most cases so. So I think enabling it by default, and to be able to disable it by config is mostly efficient. 

As for putting them on bottom, I totally agree, it is indeed more visible. 

Should I create another pl?

**Comment by firecat53** [comment]
You should be able to just add and push commits to the branch from which you created the PR.

**Comment by firecat53** [comment]
Went ahead and finished this up and merged it. Thanks!

**Pull request closed without merging**
