### PR TITLE
Add an exit option to keep the application running after each user choice

### PR DESCRIPTION
**Pull request by amtoine**
This PR adds a loop around the action selection such that the application does not close after each choice of the user.
An "exit" option also has been added to close the application properly.

Addresses #110.

### CODE REVIEW

**Comment by firecat53** [comment]
I appreciate the effort! Try out the `develop` branch and see if that behaves like you would expect after a wifi rescan. I don't feel that keeping the script open after every action is necessary, but I've been struggling to figure out how to handle the rescan. Five seconds seems reasonable to me, but I only have one device to test it with! Let me know what you think.

**Comment by firecat53** [comment]
I implemented a slightly different approach for handling the rescan. See my
comments in #111.

**Comment by amtoine** [comment]
> I appreciate the effort! Try out the `develop` branch and see if that behaves like you would expect after a wifi rescan. I don't feel that keeping the script open after every action is necessary, but I've been struggling to figure out how to handle the rescan. Five seconds seems reasonable to me, but I only have one device to test it with! Let me know what you think.
>
oooo i see :thinking: 
that could be enough you're right :open_mouth: 

let me try that out and compare with what i've done :wink: 
i'll give you feedback asap :relieved:

**Comment by amtoine** [comment]
> I implemented a slightly different approach for handling the rescan. See my comments in #111.
>
is it really in #111? :thinking: 
it links to this very PR :yum:

**Comment by amtoine** [comment]
i switch back to #110 to talk about that feature :wink:

**Comment by amtoine** [comment]
@firecat53 
do we close this now? :thinking: 

not directly connected to the new feature, but maybe overkill :wink:

**Comment by firecat53** [comment]
Closed with e84118c

**Pull request closed without merging**
